// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSVTranslationLookup
{
    internal sealed partial class Vsix
    {
        public const string Id = "CSVTranslationLookup.fa071463-3e37-49ad-a204-456ecde95eb1";
        public const string Name = "CSVTranslationLookup";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Christopher WHitley";
        public const string Tags = "";
    }
}
